apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-app-1-ingress
  namespace: default
spec:
  rules:
    - host: example-app-1.com
      http:
        paths:
          - backend:
              serviceName: example-app-1
              servicePort: 5000
