name: "Build and Push Docker Image"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docker:
    name: "Docker Build and Push"
    runs-on: self-hosted
    environment: "Docker"
    env:
      DOCKER_TLS_VERIFY: ""
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-config-inline: |
            insecure-registries = ["${{ vars.REGISTRY_HOST }}"]
            [registry."${{ vars.REGISTRY_HOST }}"]
              http = false
              insecure = true

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ vars.REGISTRY_HOST }}/${{ github.repository }}:latest
            ${{ vars.REGISTRY_HOST }}/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
