name: "Build and Push Docker Image"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docker:
    name: "Docker Build and Push"
    runs-on: self-hosted
    environment: "Docker"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: "Configure Docker for insecure registry"
        run: |
          echo '{"insecure-registries": ["${{ vars.REGISTRY_HOST }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ vars.REGISTRY_HOST }}/example-app-1:latest
            ${{ vars.REGISTRY_HOST }}/example-app-1:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
