name: "Build and Push Docker Image"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docker:
    name: "Docker Build and Push"
    runs-on: self-hosted
    environment: "Docker"
    env:
      DOCKER_TLS_VERIFY: ""
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Extract repository name"
        id: extract_repo
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-config-inline: |
            insecure-registries = ["${{ vars.REGISTRY_HOST }}"]
            [registry."${{ vars.REGISTRY_HOST }}"]
              http = false
              insecure = true

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ vars.REGISTRY_HOST }}/${{ env.REPO_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Use context
        run: kubectl config use-context octobay-api

      - name: Dry Run Deploy to K8s
        if: github.event_name == 'pull_request'
        run: kubectl apply -f deployment/ --dry-run=client

      - name: Deploy to K8s
        if: github.event_name == 'push'
        run: kubectl apply -f deployment/
